[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

upload_speed = 921600

board_build.partitions = default.csv
board_build.flash_mode = dio

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -DCONFIG_ESP32S3_SPIRAM_SUPPORT

lib_deps =
    espressif/ESP32 Deep Sleep@0.0.0+sha.8b251ab8a0
